version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/houdoku-plugins

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: download dependencies
          command: ./gradlew dependencies

      - run:
          name: build
          command: ./gradlew build

      - add_ssh_keys:
          fingerprints:
            - "e0:7c:60:d7:36:98:6d:c7:46:84:76:d4:aa:87:93:ff"

      - run:
          name: deploy
          command: .circleci/deploy.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}