version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/houdoku-plugins

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: download dependencies
          command: ./gradlew dependencies

      - run:
          name: build
          command: ./gradlew build

      - run:
          name: deploy
          command: .circleci/deploy.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}